### ISSUE TITLE
Add VCF support

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_jbrowse#10]

**Comment by jwest60** [comment]
`flatfile-to-json.pl` does most of the work here as long as we give it the correct `trackLabel` right?

i'm not sure what else there is to do other than just add [HTMLVariants](https://jbrowse.org/docs/variants.html) as an option for `trackLabel`

**Comment by almasaeed2010** [comment]
`flatfile-to-json` doesn't have a VCF option. You might need handle this one manually. IE, create the JSON yourself and add it to the file along with moving the VCF file to the location of the JBrowse data directory.

**Comment by jwest60** [comment]
the destination file path to the vcf directory i want to create starting from the data directory given in the settings is `/organism_name/data/vcf`

if i call `file_move` in the `hardwoods_jbrowse_upload_file` function, i don't understand how i'm supposed to get the organism name for the destination file path

**Comment by almasaeed2010** [comment]
The path to the data directory where organism folders live is stored in the settings:

```php
$settings = hardwoods_jbrowse_get_settings();
$data = $settings['data_dir'];
```

Now that we have that we can add the organism name to it to get the full path:

```php
$path = $data.'/'.hardwoods_jbrowse_make_slug($instance->title).'/data';
```

Note: function names might not be accurate.

**Comment by jwest60** [comment]
where does `$instance` come from?

**Comment by almasaeed2010** [comment]
you'll need to pass it in. In fact it's better to just pass the final path to the upload function rather than giving it the instance.

**Comment by jwest60** [comment]
vcf tracks can be created on [this branch](https://github.com/statonlab/hardwoods_jbrowse/tree/add-vcf-support)

there are two issues at this point:
1. each vcf track needs two files: the vcf file and the tbi file, which means we're probably going to need two file uploads on the form
2. a vcf file is _very_ large, about 1.5 GB, so a file upload might not be feasible

![image](https://user-images.githubusercontent.com/32902460/48430973-8fb82a00-e73e-11e8-8c5b-dec49982317c.png)

**Comment by jwest60** [comment]
we could maybe consider using the tripal html5 file uploader here, i'll do further research on this

**Comment by jwest60** [comment]
ditching the idea of using the html5 loader and just modifying states of the form to add a second file upload when vcf is selected as the file type, the result is something that looks like this

![image](https://user-images.githubusercontent.com/32902460/48731083-2f2b6000-ec0a-11e8-833e-3f7819923389.png)

there's also the option to provide a local directory containing the .gz and .tbi file, and at the moment this is the only option that i know for sure works

the file upload should work in theory but the upload takes too long to test

**Comment by jwest60** [comment]
tested the file upload with smaller vcf files and everything seems to be working with it now

also added further error checking to the validate form to ensure the file gets moved correctly
