### ISSUE TITLE
add ability to delete a whole instance

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_jbrowse#5]

**Comment by almasaeed2010** [comment]
this entails finding the file if it was uploaded via the form and deleting it for each track. It also needs to remove the organism directory that the module created.

**Comment by jwest60** [comment]
lets leave it to a system admin to delete instances

**Comment by almasaeed2010** [comment]
We need to add a delete button to delete the DB record but we won't need to delete the files or tracks. Let's make sure to add a message to tell the user that they need to delete the files manually and include the path to the directory they need to remove.

**Comment by almasaeed2010** [comment]
done.
